# Generated by Django 2.0.13 on 2019-11-01 03:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cine', '0004_auto_20191101_0353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcion',
            name='pelicula_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cine.Pelicula'),
        ),
    ]
