# Generated by Django 2.0.13 on 2019-11-02 03:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cine', '0005_auto_20191101_0356'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcion',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='created_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
