# Generated by Django 2.0.13 on 2019-11-02 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cine', '0006_auto_20191102_0356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pelicula',
            name='published_date',
        ),
        migrations.AlterField(
            model_name='funcion',
            name='created_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
