# Generated by Django 2.0.13 on 2019-11-02 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cine', '0007_auto_20191102_0406'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pelicula',
            old_name='text',
            new_name='descripcion',
        ),
        migrations.RenameField(
            model_name='pelicula',
            old_name='created_date',
            new_name='fecha',
        ),
        migrations.RenameField(
            model_name='pelicula',
            old_name='title',
            new_name='titulo',
        ),
    ]
