# Generated by Django 2.0.13 on 2019-11-02 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cine', '0008_auto_20191102_1849'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pelicula',
            old_name='fecha',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='pelicula',
            old_name='descripcion',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='pelicula',
            old_name='titulo',
            new_name='title',
        ),
    ]
