# Generated by Django 2.0.13 on 2019-11-02 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cine', '0009_auto_20191102_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelicula',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Titulo'),
        ),
    ]
