# Generated by Django 2.0.13 on 2019-11-02 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cine', '0010_auto_20191102_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelicula',
            name='text',
            field=models.TextField(verbose_name='Descripcion'),
        ),
    ]
